[package]
name = "subterfuge"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
fancy-regex = "0.13.0"
rand = "0.8.5"
serde = "1.0.196"
serde_json = "1.0.112"
