baseURL = "/"
title = "TinkerHub Learning Paths"
theme = "tinkerhub"
[Params]
  commentsRepo="tinkerhub/TinkerHub-Learning-Paths-Comments"
[taxonomies]
  category = "category"
  tag = "tags"
  pathType = "pathTypes"
enableEmoji = true
pygmentsUseClasses = true
#googleAnalytics = ""
[outputs]
  home =["HTML", "JSON", "RSS"]