version: '3.7'
services:
  event-management-service:
    build: ./Event-Management-Service #Location of Dockerfile
    container_name: event-management-service # Name
    environment: # Environmental variables
      - NODE_ENV=development
      - PORT=3001
      - DB_URI=mongodb+srv://event-management.bsw5xrq.mongodb.net/Event-Management-Service?authSource=%24external&authMechanism=MONGODB-X509&retryWrites=true&w=majority
    ports: # Ports mapping
      - '3001:3001'
    # To host this you could use a reverse proxy that would connect to the localhost of this computer ( or the server it is hosted at)
  interface-service:
    build: ./Interface-Service #Location of Dockerfile
    container_name: interface-service # Name
    ports: # Ports mapping
      - '3000:3000'
  auth-service:
    build: ./Auth-service #Location of Dockerfile
    container_name: auth-service # Name
    environment: # Environmental variables
      - NODE_ENV=development
      - PORT=3002
      - DB_URI=mongodb+srv://event-management.bsw5xrq.mongodb.net/Auth-Service?authSource=%24external&authMechanism=MONGODB-X509&retryWrites=true&w=majority
      - SECRET=3b41c1b1d7f99d42995f4dca87db2a630e1994946b035a1410ed52dd014ec2da
    ports: # Ports mapping
      - '3002:3002'
  ticketing-service:
    build: ./Ticketing-service #Location of Dockerfile
    container_name: ticketing-service # Name
    environment: # Environmental variables
      - NODE_ENV=development
      - EMAIL_USER=tech.events4@gmail.com
      - EMAIL_PASS=ibmdrzglxihbvzyk
      - PORT=5000
      - MONGO_URI=mongodb+srv://event-management.bsw5xrq.mongodb.net/Ticketing-Service?authSource=%24external&authMechanism=MONGODB-X509&retryWrites=true&w=majority
      - SECRET=3b41c1b1d7f99d42995f4dca87db2a630e1994946b035a1410ed52dd014ec2da
    ports: # Ports mapping
      - '5000:5000'
  payment-service:
    build: ./Payment-service #Location of Dockerfile
    container_name: payment-service # Name
    environment: # Environmental variables
      - NODE_ENV=development
      - PORT=5001
      - MONGO_URI=mongodb+srv://event-management.bsw5xrq.mongodb.net/Payment-Service?authSource=%24external&authMechanism=MONGODB-X509&retryWrites=true&w=majority
      - SECRET=3b41c1b1d7f99d42995f4dca87db2a630e1994946b035a1410ed52dd014ec2da
      - STRIPE_SECRET_KEY=sk_test_51MwkwTIU0773awQBKbTLYJ0jNVmhMMLqAWCvYxKYEb9HeFYQS4LdeOCJjXzjEihlgcCXTqUaDcNPuJ5MvDc5JIKu00EtsspduU
    ports: # Ports mapping
      - '5001:5001'