name: numpy-tutorials
channels:
  - conda-forge
dependencies:
  # For running the tutorials
  - numpy
  - scipy
  - pooch
  - matplotlib
  - pandas
  - imageio
  # For building the site
  - sphinx
  - myst-nb
  - sphinx-book-theme
  - sphinx-copybutton
  # to load the md files in binder
  - jupytext
