name: Run Python Script
true:
  schedule:
  - cron: '*/60 * * * *'
  workflow_dispatch: null
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: List files in the repository root
      run: ls -la
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r ./requirements.txt  # 假设你的脚本需要 requests 库

        '
    - env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      name: Run the script
      run: 'echo "Running the script... ${GITHUB_TOKEN}"

        python github.py "$GITHUB_TOKEN"  # 传递环境变量作为命令行参数'
notifications:
  email:
    on_failure: never
    on_success: never
